# Copyright 2023 Amazon.com and its affiliates; all rights reserved. This file is Amazon Web Services Content and may not be duplicated or distributed without permission.

version: '3'
services:
  graphsearch-api:
      build: 
        context: .
      networks:
          - graphsearch-net
      ports:
        - 5001:5001
      restart: on-failure:20

networks:
  graphsearch-net:
